name: Run tests
on: [push]
jobs:
  test-suites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install everything
        run: npm install
      - name: Angular test for dictionary
        run: |
          npm test
